-- Gendaz Leads - Schema inicial
-- Neon PostgreSQL / PostgreSQL 14+

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    full_name VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL DEFAULT 'USER',
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE campaigns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    niche VARCHAR(255) NOT NULL,
    location VARCHAR(255) NOT NULL,
    requested_quantity INTEGER NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'CREATED',
    discovered_count INTEGER NOT NULL DEFAULT 0,
    analyzed_count INTEGER NOT NULL DEFAULT 0,
    message_count INTEGER NOT NULL DEFAULT 0,
    approved_count INTEGER NOT NULL DEFAULT 0,
    sent_count INTEGER NOT NULL DEFAULT 0,
    replied_count INTEGER NOT NULL DEFAULT 0,
    interested_count INTEGER NOT NULL DEFAULT 0,
    converted_count INTEGER NOT NULL DEFAULT 0,
    blocked_count INTEGER NOT NULL DEFAULT 0,
    progress_stage VARCHAR(50),
    progress_current INTEGER NOT NULL DEFAULT 0,
    progress_total INTEGER NOT NULL DEFAULT 0,
    error_message TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_campaign_status CHECK (status IN (
        'CREATED','DISCOVERING','ANALYZING','GENERATING','COMPLETED','FAILED','PARTIAL'
    ))
);

CREATE TABLE leads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_name VARCHAR(255) NOT NULL,
    normalized_name VARCHAR(255),
    category VARCHAR(255),
    address VARCHAR(512),
    city VARCHAR(255),
    state VARCHAR(255),
    country VARCHAR(120) DEFAULT 'BR',
    phone VARCHAR(60),
    normalized_phone VARCHAR(60),
    website VARCHAR(512),
    normalized_website VARCHAR(512),
    instagram_username VARCHAR(120),
    normalized_instagram VARCHAR(120),
    instagram_url VARCHAR(512),
    instagram_status VARCHAR(30) DEFAULT 'NOT_FOUND',
    source VARCHAR(60),
    source_id VARCHAR(255),
    normalized_source_id VARCHAR(255),
    do_not_contact BOOLEAN NOT NULL DEFAULT FALSE,
    status VARCHAR(50) NOT NULL DEFAULT 'NEW',
    current_campaign_id BIGINT REFERENCES campaigns(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_lead_status CHECK (status IN (
        'NEW','ANALYZING','ANALYZED','MESSAGE_READY','APPROVED','SENT','REPLIED',
        'INTERESTED','SCHEDULED','CONVERTED','NOT_INTERESTED','DO_NOT_CONTACT','ERROR'
    )),
    CONSTRAINT chk_instagram_status CHECK (instagram_status IN ('NOT_FOUND','FOUND','UNVERIFIED')),
    CONSTRAINT uk_lead_instagram UNIQUE (normalized_instagram),
    CONSTRAINT uk_lead_website UNIQUE (normalized_website),
    CONSTRAINT uk_lead_phone UNIQUE (normalized_phone),
    CONSTRAINT uk_lead_source_id UNIQUE (normalized_source_id),
    CONSTRAINT uk_lead_name_location UNIQUE (normalized_name, city, state)
);

CREATE INDEX idx_leads_status ON leads(status);
CREATE INDEX idx_leads_dnc ON leads(do_not_contact);
CREATE INDEX idx_leads_campaign ON leads(current_campaign_id);
CREATE INDEX idx_leads_created ON leads(created_at DESC);

CREATE TABLE lead_sources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_id BIGINT NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
    source VARCHAR(60) NOT NULL,
    source_id VARCHAR(255),
    source_url VARCHAR(512),
    found_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_lead_source UNIQUE (lead_id, source, source_id)
);

CREATE TABLE lead_analysis (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_id BIGINT NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
    business_type VARCHAR(255),
    services TEXT,
    digital_presence VARCHAR(60),
    uses_booking_system BOOLEAN,
    booking_system_status VARCHAR(30) DEFAULT 'UNKNOWN',
    detected_system VARCHAR(255),
    manual_attendance_signals TEXT,
    pain_points TEXT,
    commercial_opportunity TEXT,
    opportunity_score INTEGER,
    reasoning_summary TEXT,
    model VARCHAR(120),
    analyzed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_lead_analysis UNIQUE (lead_id),
    CONSTRAINT chk_booking_status CHECK (booking_system_status IN ('NOT_IDENTIFIED','IDENTIFIED','PROBABLE','UNKNOWN')),
    CONSTRAINT chk_score_range CHECK (opportunity_score BETWEEN 0 AND 100)
);

CREATE TABLE lead_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_id BIGINT NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
    message_text TEXT NOT NULL,
    edited BOOLEAN NOT NULL DEFAULT FALSE,
    approved BOOLEAN NOT NULL DEFAULT FALSE,
    generated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    edited_at TIMESTAMPTZ,
    CONSTRAINT uk_lead_message UNIQUE (lead_id)
);

CREATE TABLE campaign_leads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_id BIGINT NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE,
    lead_id BIGINT NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
    added_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_campaign_lead UNIQUE (campaign_id, lead_id)
);

CREATE INDEX idx_campaign_leads_campaign ON campaign_leads(campaign_id);
CREATE INDEX idx_campaign_leads_lead ON campaign_leads(lead_id);

CREATE TABLE lead_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_id BIGINT NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
    campaign_id BIGINT REFERENCES campaigns(id) ON DELETE SET NULL,
    event_type VARCHAR(60) NOT NULL,
    event_metadata TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_lead_events_lead ON lead_events(lead_id);
CREATE INDEX idx_lead_events_created ON lead_events(created_at DESC);

CREATE TABLE message_sends (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_id BIGINT NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
    campaign_id BIGINT REFERENCES campaigns(id) ON DELETE SET NULL,
    provider VARCHAR(60) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'QUEUED',
    attempts INTEGER NOT NULL DEFAULT 0,
    last_attempt_at TIMESTAMPTZ,
    next_attempt_at TIMESTAMPTZ,
    result TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_send_status CHECK (status IN ('QUEUED','SENDING','SENT','FAILED','SKIPPED'))
);

CREATE INDEX idx_message_sends_status ON message_sends(status);
CREATE INDEX idx_message_sends_next ON message_sends(next_attempt_at);
