-- Gendaz Leads - Message Templates - V3
-- Templates de mensagem para abordagem via WhatsApp.

CREATE TABLE message_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    template_text TEXT NOT NULL,
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_message_template_default UNIQUE (is_default) WHERE is_default = TRUE
);

-- Inserir abordagem padrão inicial
INSERT INTO message_templates (name, template_text, is_default)
VALUES (
    'Abordagem padrão',
    'Olá {{nome}}, tudo bem?

Conheci a {{nome}} e queria apresentar o Gendaz.
Ele ajuda a organizar agenda, clientes, financeiro e clientes que estão há algum tempo sem retornar.

Se quiser conhecer antes: gendaz.site

Posso te explicar rapidamente como funciona?',
    TRUE
);