-- Gendaz Leads - Message Templates and Message Sends - V4
-- Templates de mensagem para abordagem via WhatsApp.
-- Partial unique index garante somente um template default ativo.

CREATE TABLE message_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    template_text TEXT NOT NULL,
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now
);

-- Garante apenas um template default por vez (index parcial)
CREATE UNIQUE INDEX uq_message_template_default
ON message_templates (is_default)
WHERE is_default = TRUE;

-- Inserir abordagem padrão inicial (apenas se nao existir)
DO $$
BEGIN
    INSERT INTO message_templates (name, template_text, is_default)
    SELECT 'Abordagem padrão', 'Olá {{nome}}, tudo bem?

Conheci a {{nome}} e queria apresentar o Gendaz.
Ele ajuda a organizar agenda, clientes, financeiro e clientes que estão há algum tempo sem retornar.

Se quiser conhecer antes: gendaz.site

Posso te explicar rapidamente como funciona?', TRUE
WHERE NOT EXISTS (SELECT 1 FROM message_templates WHERE is_default = TRUE);
END$$;

-- Adicionar colunas a message_sends para rastreamento completo de envio
ALTER TABLE message_sends ADD COLUMN IF NOT EXISTS message_text_snapshot TEXT;
ALTER TABLE message_sends ADD COLUMN IF NOT EXISTS recipient_snapshot VARCHAR(255);
ALTER TABLE message_sends ADD COLUMN IF NOT EXISTS template_id BIGINT REFERENCES message_templates(id) ON DELETE SET NULL;
ALTER TABLE message_sends ADD COLUMN IF NOT EXISTS request_id VARCHAR(255);
ALTER TABLE message_sends ADD COLUMN IF NOT EXISTS provider_message_id VARCHAR(255);
ALTER TABLE message_sends ADD COLUMN IF NOT EXISTS error_code VARCHAR(50);
ALTER TABLE message_sends ADD COLUMN IF NOT EXISTS queued_at TIMESTAMPTZ;
ALTER TABLE message_sends ADD COLUMN IF NOT EXISTS sent_at TIMESTAMPTZ;

-- Atualizar constraint de status para incluir DELIVERY_UNKNOWN
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'chk_send_status'
    ) THEN
        -- Constraint ja existe, altera para incluir DELIVERY_UNKNOWN
        EXECUTE 'ALTER TABLE message_sends DROP CONSTRAINT chk_send_status';
    END IF;
    EXECUTE 'ALTER TABLE message_sends ADD CONSTRAINT chk_send_status CHECK (status IN (
        ''QUEUED'',''SENDING'',''SENT'',''FAILED'',''SKIPPED'',''DELIVERY_UNKNOWN''
    ))';
    RAISE NOTICE 'Constraint de status atualizada para incluir DELIVERY_UNKNOWN';
END$$;

-- Criar index unico em request_id para idempotencia (aparencia condicional)
CREATE UNIQUE INDEX IF NOT EXISTS uq_message_sends_request_id
ON message_sends (request_id)
WHERE request_id IS NOT NULL;

COMMENT ON TABLE message_templates IS 'Templates de mensagem para abordagem via WhatsApp';
COMMENT ON INDEX uq_message_template_default IS 'Index parcial: apenas um template pode ser default ao mesmo tempo';
COMMENT ON INDEX uq_message_sends_request_id IS 'Index unico em requestId para idempotencia de envio';